name: Build AppSync Unified

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: macos-12  # Use macOS 14 with Xcode 16

    steps:
      # Step 1: Checkout the AppSync Unified repository
      - name: Checkout AppSync Unified repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies via Homebrew
      - name: Install dependencies via Homebrew
        run: |
          brew update
          brew install dpkg ldid

      # Step 3: Install Theos (checkout specific commit e045ac7)
      - name: Install Theos at specific commit e045ac7
        run: |
          echo $HOME
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          #git clone https://github.com/theos/theos.git $HOME/theos
          cd $HOME/theos
          git checkout e045ac7  # Checkout the specific commit
          git submodule update --init --recursive
        env:
          THEOS: $HOME/theos

      # Step 4: Set up Theos environment variables
      - name: Set up Theos environment
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH

      # Step 5: Verify Xcode and Swift versions (optional)
      - name: Verify Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      # Step 6: Build AppSync Unified
      - name: Build AppSync Unified
        run: |
          make
          make package

      # Step 7: Find the generated .deb files
      - name: Find generated .deb files
        id: find_deb
        run: |
          deb_path=$(find . -type f -name '*.deb' | head -n 1)
          if [ -z "$deb_path" ]; then
            echo "No .deb file found."
            exit 1
          fi
          echo "deb_path=$deb_path" >> $GITHUB_ENV

      # Step 8: Upload the generated .deb as an artifact
      - name: Upload Artifact
        if: env.deb_path != ''
        uses: actions/upload-artifact@v3
        with:
          name: AppSync-Unified
          path: ${{ env.deb_path }}
